### ISSUE TITLE
User request status check command

### ISSUE THREAD

**Issue by pixelcort** [yetanotherx/ModTRS#21]
As discussed in http://nerd.nu/forum/index.php?p=/discussion/2657/suggestions-for-pve it would be nice if end users had a command to check the status of their requests. 

This is distinct from notifications; this would be a command users could use at any time, useful if they were afk for awhile. 

This tracks such a feature.

**Comment by yetanotherx** [comment]
Added, and will be in the next version. Players without permission to use /check can now use /check, but it will only show the requests they created.

**Comment by pixelcort** [comment]
Note to self: The commit that added this is e7284a3454212a87787b89b91572659d20dbd73d.
