### ISSUE TITLE
Purge command

### ISSUE THREAD

**Issue by sugy87** [yetanotherx/ModTRS#40]
Hello if it is possible to insert a PURGE command
so you can completly delete the CLOSED tickets out of the data base.

Thank you

**Comment by yetanotherx** [comment]
Delete the database. Done!

**Comment by sugy87** [comment]
but if is it posible to give a command. so IG admin can purge it. and only the CLOSED ones

**Comment by yetanotherx** [comment]
Nope. That's something that should only be done by a server admin anyway.

**Comment by sugy87** [comment]
Ok ok. i just wrote the question on his request if it is possible to insert
